version: '3.4'

# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}:${DOCKER_TAG:-latest}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app_prod
      args:
        PYTHON_BASE: ${PYTHON_BASE:-base} # Valid values: base, cuda
        PORT: ${PORT:-80}
    # Deploy
    volumes:
      - ./Fooocus:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    tty: true # Required for pygit2.Repository
    ports:
      # HTTP
      - target: ${PORT:-80}
        published: ${HTTP_PORT:-80}
        protocol: tcp
